name: CI

on:
  push:
    branches:
      - main

jobs:
  run-pnpm-script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.4.0
      
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
          cache: 'pnpm'  # caches pnpm dependencies

      - name: install dependencies
        run: pnpm install --frozen-lockfile  # installs dependencies